### ISSUE TITLE
won't connect, no information on what fails

### ISSUE THREAD

**Issue by dahtah** [gdkrmr/lsp-julia#10] opened 2019-03-04 12:27 UTC
I've tried setting up lsp-julia to use with ess-julia-mode and it fails silently. The modeline displays "LSP[Disconnected]". lsp-describe-session is blank even with lsp-print-io set to 't. LanguageServer runs fine when I start it by hand. Not sure where to go from here? Thanks for any pointers!

**Comment by non-Jedi** [comment] 2019-04-20 23:48
This isn't an issue I've personally seen, but it sounds similar to the issue described in https://discourse.julialang.org/t/using-lsp-julia/20085. Does anything in that thread help you? The other issue I'm aware of is the long startup time for the julia language server; you could try try setting `lsp-julia-timeout` to a higher value to see if that's the issue you're having. Beyond that, you'll probably have to ask someone more familiar with upstream lsp for help in debugging.

**Comment by dahtah** [comment] 2019-04-23 08:05
Thanks. No, I'd seen that, doesn't seem to help. What does help is switching to spacemacs, and using the julia layer, but only on emacs 25. It also fails on a more recent version of emacs. My conclusion is that emacs+julia lsp is pretty fragile at this stage. Will investigate more.

**Comment by non-Jedi** [comment] 2019-04-23 11:07
Weird. I've actually personally been using eglot rather than lsp lately (see LanguageServer.jl wiki), but that has its own set of issues including crashing the language server every time a file is saved.

**Comment by gdkrmr** [comment] 2019-05-12 17:37
Should be fixed now, see https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/341.

**Comment by gdkrmr** [comment] 2019-09-04 07:59
assuming that this is fixed...

**Closed as completed by gdkrmr** 2019-09-04 07:59 UTC

**Comment by Ionizing** [comment] 2020-09-20 13:32
I just ran across the same issue as @dahtah, and I followed the steps of troubleshooting said in https://discourse.julialang.org/t/using-lsp-julia/20085, nothing appears in *lsp-session*. Here is what I did to reproduce the issue:

- if I install `lsp-julia` straight from melpa via appending `(package! lsp-julia)` to `~/.doom.d/packages.el`, `lsp-mode` just can't find `lsp-julia`, even if I manually add the hooks. So I have to install configure `lsp-julia` manually.
- Append the following stuff to `~/.doom.d/config.el` and `M-x doom/reload`
```elisp
;; julia stuff
(require 'julia-mode)
(push "~/.emacs.d/.local/straight/repos/lsp-julia" load-path)
(require 'lsp-julia)
(require 'lsp-mode)
(add-hook 'julia-mode-hook #'lsp)
(add-hook 'julia-mode-hook #'lsp-mode)
```
- Now `lsp-julia` can be activated in `julia-mode`
- However about 10 secs after showing "Connected to [julia-ls: xxxxx status:starting]", an error shows that "Server julia-ls:xxxx status:starting exited with status exit. Do you want to restart it?"
- `M-: (setq lsp-print-io t)` and `M-: (setq lsp-log-io t)` , then `M-x lsp-describe-session` and `M-x lsp`, nothing shows in the *lsp-session* buffer, just like that:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/17506747/93712408-492c8580-fb88-11ea-9896-cae12c9040ad.png">

I wonder if I just missed something because I can never access the log of `julia-ls`, or I need an executable named with `julia-ls` in `PATH`?

Here is my environment:

Emacs-plus 27.1 with doom-emacs
macOS 10.15.6
Julia: 1.5
lsp-julia: version of 2020-9-8
All the dependencies of julia's language server are installed. I can run the language server manually with
```
❯ julia --startup-file=no --history-file=no "-e using LanguageServer, Sockets, SymbolServer; server = LanguageServer.LanguageServerInstance( stdin, stdout, false, \"/home/francois/.julia/environments/v1.5\", \"\",Dict()); server.runlinter = true; run(server);"
[ Info: Started symbol server
[ Info: store set
```

**Comment by Ionizing** [comment] 2020-09-23 09:57
Update:

After some STFW, I typed
```shell
julia --startup-file=no --history-file=no "-e using LanguageServer, Sockets, SymbolServer; server = LanguageServer.LanguageServerInstance( stdin, stdout, false, \"/Users/ionizing/.julia/environments/v1.5\", \"\",Dict()); server.runlinter = true; run(server);"
```
and the error message finally showed

```
[ Info: Started symbol server
[ Info: JuliaZH not stored on disc
ERROR: EOFError: read end of file

stderr from client process:

ERROR: LoadError: MethodError: no method matching is_stdlib(::Pkg.Types.Context, ::Base.UUID)
Stacktrace:
 [1] cache_package(::Pkg.Types.Context, ::Base.UUID, ::Dict{Any,Any}, ::String) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/symbols.jl:215
 [2] cache_package(::Pkg.Types.Context, ::Base.UUID, ::Dict{Any,Any}) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/symbols.jl:190
 [3] top-level scope at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/server.jl:39
 [4] include(::Function, ::Module, ::String) at ./Base.jl:380
 [5] include(::Module, ::String) at ./Base.jl:368
 [6] exec_options(::Base.JLOptions) at ./client.jl:296
 [7] _start() at ./client.jl:506
in expression starting at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/server.jl:33

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] request(::SymbolServerProcess, ::Symbol, ::Array{String,1}) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:68
 [3] cache_package(::SymbolServerProcess, ::Array{Base.UUID,1}) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:235
 [4] cache_package at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:229 [inlined]
 [5] load_package_cache(::SymbolServerProcess, ::Base.UUID) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:173
 [6] load_project_packages(::SymbolServerProcess) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:95
 [7] getstore at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:101 [inlined]
 [8] run(::LanguageServerInstance) at /Users/ionizing/.julia/packages/LanguageServer/XXTJb/src/languageserverinstance.jl:36
 [9] top-level scope at none:1
caused by [exception 1]
EOFError: read end of file
Stacktrace:
 [1] read(::Base.PipeEndpoint, ::Type{UInt8}) at ./stream.jl:866
 [2] read(::Base.Process, ::Type{UInt8}) at ./io.jl:341
 [3] deserialize at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773 [inlined]
 [4] deserialize(::Base.Process) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:760
 [5] request(::SymbolServerProcess, ::Symbol, ::Array{String,1}) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:60
 [6] cache_package(::SymbolServerProcess, ::Array{Base.UUID,1}) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:235
 [7] cache_package at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:229 [inlined]
 [8] load_package_cache(::SymbolServerProcess, ::Base.UUID) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:173
 [9] load_project_packages(::SymbolServerProcess) at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:95
 [10] getstore at /Users/ionizing/.julia/packages/SymbolServer/KebKX/src/SymbolServer.jl:101 [inlined]
 [11] run(::LanguageServerInstance) at /Users/ionizing/.julia/packages/LanguageServer/XXTJb/src/languageserverinstance.jl:36
 [12] top-level scope at none:1
```

Maybe the error message above could help to locate the issue ...

**Comment by gdkrmr** [comment] 2020-09-23 11:24
I don't really know how doom emacs works, have you tried the suggestions in https://github.com/non-Jedi/lsp-julia/issues/20#issuecomment-682235411 ?

**Comment by Ionizing** [comment] 2020-09-27 12:28
I'm afraid the patch listed in that reply has less effect on my machine ...
