### ISSUE TITLE
Jump to definition not working between files

### ISSUE THREAD

**Issue by prassee** [gdkrmr/lsp-julia#25] opened 2020-04-24 02:05 UTC
I'm uisng the latest master with Julia 1.4. Basic LSP functions do work but the jumpt to definition  and find references. In case of definitions, I can within the file but not to functions or variables defined in other files.

I got the following warning message

`Warning (lsp-mode): Failed to process xref entry for filename ’’: Read error: Is a directory, /data/dataworkspace/vamana-ts-modelling`

**Comment by gdkrmr** [comment] 2020-04-25 12:22
Does it work with Julia 1.3? Julia 1.4 support does not work properly yet. How did you install `lsp-julia`?

**Comment by prassee** [comment] 2020-04-26 05:46
I used (https://github.com/gdkrmr/lsp-julia) clone of lsp-julia to try with Julia1.4 (since gdkrmr repo seems to use the latest LangServer). 
OTTH, while using this repo I got the same error with Julia 1.3.

I installed lsp-julia by cloning https://github.com/non-Jedi/lsp-julia repo and adding to lsp-julia.jl to the loadpath of emacs.

**Comment by prassee** [comment] 2020-04-30 04:27
just curious to know any updates about this

**Comment by prassee** [comment] 2020-04-30 04:42
I have created another issue I found after updating to the latest code - https://github.com/non-Jedi/lsp-julia/issues/27

**Comment by gdkrmr** [comment] 2020-04-30 08:33
For me https://github.com/non-Jedi/lsp-julia works with julia 1.3 and https://github.com/gdkrmr/lsp-julia works with 1.4 (haven't done any tests with 1.3) but flycheck integration does not work, which is why I haven't merged yet.

**Comment by ghost** [comment] 2020-05-01 00:36
I'm also facing the same issue with the following 
- Julia 1.3.1
- lsp-julia installed via quelpa
- Emacs 26.3

What works?
- autocompletion
- jump to definition (with in the file)

What not works
- jump to definition outside the file for eg. those  included in to scope via `include` means files included with in a project. However it works for those added as a Pkg dependency.

**Comment by gdkrmr** [comment] 2020-05-02 16:28
what is the exact version of `lsp-julia`? The one from https://github.com/gdkrmr/lsp-julia currently has issues.

**Comment by ghost** [comment] 2020-05-03 01:27
I'm using `non-jedi` version https://github.com/non-Jedi/lsp-julia

**Comment by gdkrmr** [comment] 2020-05-03 14:55
that works fine for me. Sometimes `LanguageServer.jl` doesn't find the symbol. But seems to be a current limitation of `LanguageServer.jl`

**Comment by ghost** [comment] 2020-05-04 03:25
I dont think so as the more specific case is 
let say I include utils.jl file in main.jl

util.jl
```

function to_upper(x::String)::String
     return uppercase(x)
end
```

main.jl

```
include("utils.jl")

lang = "julia"
lang = to_upper(lang)
to_lower(lang)

function to_lower(x::String)
    return lower_case(x)
end
```

In the above code, my specific issue is jump-to-definition :- 

but works for 
- `to_lower`

doesn't work for 
- `include("utils.jl")`
- `to_upper(lang)`

and ends up with a warning

```
Warning (lsp-mode): Failed to process xref entry for filename ’’: Read error: Is a directory
```
However the same behaviour works in VSCode hence it should not be  issue from `LanguageServer`. Based on the warning message, I guess lsp-julia could not infer the mapping between functions and the respective files where they are defined.

OTTH, jump-to-definition works for all the modules where are loaded in to LOAD_PATH. 

Hope I made it clear for everyone.
(Note :- I've also tried https://github.com/non-Jedi/eglot-jl and observed the same behavior as explained above.)

**Comment by non-Jedi** [comment] 2020-05-05 11:51
Hi @prasannakog thanks for the good reproducer. For anyone else following along, the `main.jl`/`utils.jl` example above actually works inside a package, but it fails outside of a package because LanguageServer.jl uses a uri of "file://utils.jl" if outside of a package. I will file an issue with upstream.

**Comment by prassee** [comment] 2020-05-05 12:38
> Hi @prasannakog thanks for the good reproducer. For anyone else following along, the `main.jl`/`utils.jl` example above actually works inside a package, but it fails outside of a package because LanguageServer.jl uses a uri of "file://utils.jl" if outside of a package. I will file an issue with upstream.

Thanks @non-Jedi for taking this forward. I should have attached the json-log in my issue desc I would try to give as much as details if I found any in the future.

**Comment by ghost** [comment] 2020-06-01 02:42
looks like the related issue on the upstream repo got fixed , just curious to know any updates.

**Comment by ghost** [comment] 2020-07-09 16:00
@non-Jedi any updated on this

**Comment by non-Jedi** [comment] 2020-07-09 16:08
That's up to @gdkrmr to update the versions bundled with lsp-julia. It's fixed upstream.

**Comment by ghost** [comment] 2020-07-09 16:09
Thanks ... but @gdkrmr fork of lsp-julia doesn't have issues feature enabled.

**Comment by non-Jedi** [comment] 2020-07-09 16:38
He maintains this repo as well

**Comment by gdkrmr** [comment] 2020-07-09 17:35
I am maintaining this repository and use my fork as the development version. `master` on my repo is currently not working without issues. I would have merged it a long time ago. There were/are numerous open issues on `lsp-mode` and `LanguageServer.jl` to figure this out and some patches have been merged but without success. The whole thing seems to be the communication between `lsp-mode` and `LanguageServer.jl` and I am not knowledgeable in the lsp specification. If you want to contribute, @prasannakog, I suggest you start at figuring out what about the communication between `eglot` <-> `LanguagServer.jl` or `vscode` <-> `LanguageServer.jl`is different from `lsp-mode` <-> `LanguageServer.jl`.

**Comment by gdkrmr** [comment] 2020-08-27 15:48
Is this working now? Please update according to https://github.com/non-Jedi/lsp-julia/issues/20#issuecomment-682031361 and report back.

**Comment by spraharsh** [comment] 2020-09-03 17:02
It solved the issue for me. It might help to make `lsp-julia-default-environment` to `"~/.julia/environments/v1.5"` so that users may not need to go down the rabbit hole. Thank you!

**Comment by gdkrmr** [comment] 2020-09-04 08:07
Yes, I don't really have a good solution for setting the default environment. I guess the solution is to query `julia --version`.

**Closed as completed by gdkrmr** 2020-09-04 08:07 UTC
